### ISSUE TITLE
good job setting up the site -- a few more changes needed

### ISSUE THREAD

**Issue by tyson-swetnam** [eleroy3/KEYS2022#1]
New site looks good. Congratulations on getting it set up.

A couple more suggestions:

- [x] update the `mkdocs.yml` nav tree to remove or update the `/methods` and `/languages` sections, given that what you're going to be working in is different than what Shruti did last year.
- [ ] Create new sections in the nav tree which reflect what you're working on (Google Earth Engine), STAC Catalogs, Awesome Community Datasets, etc.
- [x] on your logbook -- you don't have to do one EVERY day, just on the dates you work or want to record that you made relevant updates.

**Comment by eleroy3** [comment]
Sounds good about the logbook!
